---
- name: Create group
  become: true
  group: name="{{rbenv_user}}" gid=1001

- name: Add user
  become: true
  user: name="{{rbenv_user}}" uid=501 state=present groups="{{rbenv_user}}" shell=/bin/bash

- name: Make sure we have a 'wheel' group
  become: true
  group: name=wheel state=present

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Add sudoers users to wheel group
  become: true
  user: name="{{rbenv_user}}" groups=wheel append=yes state=present createhome=yes
